"""
Node: Reflection & Critic Agent
===============================
Analyzes the natural language insights generated by the Analyst node
against the raw database query results to ensure absolute correctness.
Detects hallucinations, mathematical errors, or factual mismatches.
"""
from __future__ import annotations
import json
import re
import structlog
from backend.agent.state import AnalyticsState
from backend.agent.llm import call_llm

log = structlog.get_logger(__name__)

async def review_insights(state: AnalyticsState) -> AnalyticsState:
    """
    Critic Node.
    Validates insights against raw SQL query execution results.
    """
    question = state.get("user_question", "")
    sql = state.get("sql_query", "")
    query_results = state.get("query_results", {})
    insights = state.get("insights", [])
    
    critic_retry = state.get("critic_retry_count", 0)
    
    # If no insights or query results, skip validation
    if not insights or not query_results or not query_results.get("rows"):
        log.info("critic.skipped", reason="empty insights or query results")
        return {
            **state,
            "insights_validated": True,
            "critic_feedback": ""
        }
        
    log.info("critic.started", critic_retry_count=critic_retry)

    # Format raw query results for prompt context
    cols = query_results.get("columns", [])
    rows = query_results.get("rows", [])
    
    # Format rows up to first 50 to prevent context bloat
    rows_truncated = rows[:50]
    results_str = f"Columns: {cols}\nRows (truncated to 50):\n"
    for r in rows_truncated:
        results_str += f"  {list(r)}\n"
        
    insights_str = "\n".join(f"• {ins}" for ins in insights)

    prompt = f"""You are an Expert Data Analyst Auditor and Critic Agent.
Your single goal is to review the natural language insights generated by another AI assistant and cross-reference them with the absolute ground-truth raw query results returned by the database.

User's Original Question: "{question}"
SQL Query Executed:
```sql
{sql}
```

Database Raw Query Results:
{results_str}

Generated Insights under review:
{insights_str}

AUDIT RULES:
1. MATHEMATICAL CHECK: Verify every number, percentage, count, and sum mentioned in the insights. Calculate them against the raw rows. If any value is mathematically incorrect or misrepresented, fail the validation.
2. TRUTHFULNESS: Check for hallucinations. If the assistant claims "revenue dropped in category X" but the category is not present in the data, or the numbers show an increase, fail the validation.
3. CONTEXTUAL SCOPE: Ensure the insights match the timeframe and entities of the query. For example, if the data is for 2025, the insights must not mention 2026 or 2024 unless it is a valid comparative insight explicitly supported by comparative rows.
4. EMPTY RESULTS: If the database returned zero rows or empty rows, the insights must not invent any data trends.

Determine if the insights are 100% accurate and mathematically correct.
If they are correct, set "insights_validated" to true and leave "critic_feedback" empty.
If they contain any mismatch, hallucination, or error, set "insights_validated" to false and write the exact mismatch description in "critic_feedback".

Respond ONLY with this JSON structure:
{{
  "insights_validated": <true|false>,
  "critic_feedback": "<description of the issue or empty string>"
}}"""

    try:
        resp = await call_llm(
            messages=[{"role": "user", "content": prompt}],
            task="routing", # Fast model
            max_tokens=300,
            temperature=0.0,
        )
        
        raw = resp.content.strip()
        json_match = re.search(r'(\{.*\})', raw, re.DOTALL)
        raw_json = json_match.group(1) if json_match else raw
        if "```" in raw_json:
            raw_json = raw_json.split("```")[1].replace("json", "").strip()
            
        result = json.loads(raw_json)
        validated = bool(result.get("insights_validated"))
        feedback = result.get("critic_feedback", "")
    except Exception as exc:
        log.warning("critic.llm_parse_failed", error=str(exc))
        # Fallback to passing if LLM fails, ensuring the agent pipeline doesn't hang
        validated = True
        feedback = ""

    if validated:
        log.info("critic.passed")
        return {
            **state,
            "insights_validated": True,
            "critic_feedback": "",
            "error": None
        }
    else:
        log.warning("critic.failed", feedback=feedback)
        return {
            **state,
            "insights_validated": False,
            "critic_feedback": feedback,
            "critic_retry_count": critic_retry + 1,
            "error": f"Critic reflection failed: {feedback}"
        }
