"""
Node: SQL DBA Reviewer Agent
============================
Acts as a ClickHouse database administrator. It reviews the generated SQL query
against security, syntax, and business rules before execution. If validation fails,
it generates detailed feedback to correct the SQL.
"""
from __future__ import annotations
import json
import re
import structlog
from backend.agent.state import AnalyticsState
from backend.agent.llm import call_llm

log = structlog.get_logger(__name__)

# Strict rule check on the Python side before hitting LLM (fast, lightweight guardrails)
def _fast_regex_pre_check(sql: str, datasource_id: str) -> str | None:
    """Perform quick regex syntax & business logic checks."""
    if not sql:
        return "Empty SQL query."
        
    sql_upper = sql.upper()
    
    # 1. Safety check
    from backend.agent.nodes.sql_gen import _is_safe_sql
    is_safe, reason = _is_safe_sql(sql)
    if not is_safe:
        return f"Safety violation: {reason}"
        
    # 2. ClickHouse business rule checks
    if datasource_id == "limese":
        # Cancelled/Returned exclusion check for combined_sales_final
        if "COMBINED_SALES_FINAL" in sql_upper:
            # Check for final_status filter
            status_match = re.search(r"FINAL_STATUS\s+NOT\s+IN\s*\(", sql_upper)
            if not status_match:
                return (
                    "Business rule violation: You must ALWAYS exclude cancelled or returned orders "
                    "when querying 'combined_sales_final'. Please add: "
                    "final_status NOT IN ('cancelled','Cancelled','CANCELLED','returned','Returned')"
                )
            
            # Check for revenue/sales field selection
            if "REVENUE" in sql_upper or "SALES" in sql_upper:
                # Should not select order_price as revenue
                if "ORDER_PRICE" in sql_upper and "ROW_SUBTOTAL" not in sql_upper:
                    return (
                        "Business rule violation: For revenue queries on 'combined_sales_final', "
                        "you must use 'row_subtotal' as the revenue column. 'order_price' contains full order values, "
                        "which results in double-counting when grouped by line item."
                    )
        
        # ClickHouse function checks
        if " LAG(" in sql_upper or " LEAD(" in sql_upper:
            return "ClickHouse syntax error: Use lagInFrame() instead of lag(), and leadInFrame() instead of lead()."
            
    return None


async def review_sql(state: AnalyticsState) -> AnalyticsState:
    """
    DBA Review Node.
    Validates SQL query safety, compliance, and correctness.
    """
    sql = state.get("sql_query", "")
    datasource_id = state.get("datasource_id", "")
    question = state.get("user_question", "")
    intent = state.get("intent", {})
    rephrased = intent.get("rephrased_question") or question
    
    # Initialize count if not set
    review_count = state.get("review_retry_count", 0)
    
    # Upstream generation error exists, propagate it
    if state.get("error") and not state.get("sql_query"):
        return state
        
    log.info("sql_reviewer.started", review_count=review_count, sql_preview=sql[:150])
    
    # 1. Run fast local check
    local_err = _fast_regex_pre_check(sql, datasource_id)
    if local_err:
        log.warning("sql_reviewer.local_check_failed", error=local_err)
        return {
            **state,
            "sql_validated": False,
            "dba_feedback": local_err,
            "review_retry_count": review_count + 1,
            "error": f"DBA Review failed: {local_err}"
        }
        
    # 2. Query LLM to perform deep semantic review against instructions
    prompt = f"""You are a Database Administrator (DBA) reviewing a SQL query generated by an AI assistant for a database.
Your job is to ensure the query is syntactically correct, safe, and complies with all database business rules.

User's Original Question: "{question}"
Rephrased Standalone Question: "{rephrased}"
Database Type / Datasource: "{datasource_id}"

Generated SQL Query under review:
```sql
{sql}
```

CLIKHOUSE & DATABASE COMPLIANCE RULES:
1. EXCLUDE CANCELLED ORDERS: When querying `combined_sales_final`, the query MUST explicitly exclude cancelled/returned orders: `final_status NOT IN ('cancelled','Cancelled','CANCELLED','returned','Returned')`.
2. REVENUE COLUMN: For revenue/sales, use `row_subtotal`. NEVER use `order_price` (this is the full order total, grouping by line items will multiply the revenue incorrectly).
3. UNITS COLUMN: For units/quantities, use `quantity_ordered`. NEVER use `shipped_qty` (always 0).
4. DATE FILTERING: date_created >= '2025-01-01'. Do NOT use toYear(date_created) or dynamic timezone functions.
5. TABLE ALIASES: All columns in joins MUST be prefixed with correct table aliases.
6. WINDOW FUNCTIONS: ClickHouse does not support standard lag() or lead(). You MUST use lagInFrame() or leadInFrame().
7. SELECT CLAUSE: If the user asks ONLY for revenue, the query must NOT select quantities/units unless explicitly asked.
8. safety: Query must start with SELECT and have NO modifying queries (INSERT, UPDATE, DELETE, etc.).

Analyze the generated SQL. If it violates any rules or has syntax bugs, set "sql_validated" to false and explain the exact issue in "dba_feedback".
If the SQL is completely correct and ready to execute, set "sql_validated" to true and leave "dba_feedback" empty.

Respond ONLY with this JSON structure:
{{
  "sql_validated": <true|false>,
  "dba_feedback": "<description of the issue or empty string>"
}}"""

    try:
        resp = await call_llm(
            messages=[{"role": "user", "content": prompt}],
            task="routing", # Use fast model for routing/review
            max_tokens=300,
            temperature=0.0,
        )
        
        raw = resp.content.strip()
        json_match = re.search(r'(\{.*\})', raw, re.DOTALL)
        raw_json = json_match.group(1) if json_match else raw
        if "```" in raw_json:
            raw_json = raw_json.split("```")[1].replace("json", "").strip()
            
        result = json.loads(raw_json)
        validated = bool(result.get("sql_validated"))
        feedback = result.get("dba_feedback", "")
    except Exception as exc:
        log.warning("sql_reviewer.llm_parse_failed", error=str(exc))
        # Fall back to passing if LLM fails to review, preventing pipeline block
        validated = True
        feedback = ""
        
    if validated:
        log.info("sql_reviewer.passed")
        return {
            **state,
            "sql_validated": True,
            "dba_feedback": "",
            "error": None
        }
    else:
        log.warning("sql_reviewer.failed", feedback=feedback)
        return {
            **state,
            "sql_validated": False,
            "dba_feedback": feedback,
            "review_retry_count": review_count + 1,
            "error": f"DBA Review failed: {feedback}"
        }
